<template>
  <v-container bg fill-height text-center>
    <v-row no-gutters>
      <v-col cols="12" sm="3">
        <v-row v-for="n in 3" :key="n">
          <v-col>
            <detail :name="n" title="title" text="text" actions="actions" />
          </v-col>
        </v-row>
      </v-col>

      <v-col cols="12" sm="6">
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <img :src="getImage" usemap="#image-map" class="mtResultImage" />

        <map name="image-map">
          <area
            target="_blank"
            alt="apple"
            title="apple"
            href="infosheet"
            coords="53,60,195,195"
            shape="rect"
          />
          <area
            target="_blank"
            alt="antwerpen"
            title="antwerpen"
            href="infosheet"
            coords="285,356,375,433"
            shape="rect"
          />
        </map>
      </v-col>

      <v-col cols="12" sm="3">
        <v-row>
          <mtIcon icon="oog"></mtIcon>
          <mtIcon icon="appel"></mtIcon>
        </v-row>
        <v-row>
          <mtIcon icon="bij"></mtIcon>
          <mtIcon icon="gasmasker"></mtIcon>
        </v-row>
        <v-row>
          <mtIcon icon="koelkast"></mtIcon>
          <mtIcon icon="thermos"></mtIcon>
        </v-row>
        <v-row>
          <mtIcon icon="wolk"></mtIcon>
          <mtIcon icon="zonnecreme"></mtIcon>
        </v-row>
        <v-row>
          <textarea
            class="resultInfoArea"
            name="info"
            id="info"
            cols="30"
            rows="10"
          >
This is the presentation screen.
No data available yet, it is only meant to demonstrate 3 possibilities.

The image in the center is a so called 'image-map'.  
Hover over the image and find the 2 area's that will forward you to more detailed info.
</textarea
          >
        </v-row>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import detail from './mtOutputDetail';
import mtIcon from './mtIcon';

export default {
  components: { detail, mtIcon },
  computed: {
    getImage: () => {
      let test = require('@/assets/rekenenMetGroen.png');
      console.log(test);
      return test.default;
    }
  }
};
</script>

<style>
.mtResultImage {
  height: 40em;
  width: 30em;
}

.resultInfoArea {
  width: 15em;
  height: 22em;
  background-color: aliceblue;
}
</style>
